### PR TITLE
Postgres integration (along with examples)

### PR DESCRIPTION
**Pull request by shravancr95**

### CODE REVIEW

**Comment by procoder-net** [comment]
can you please only edit and commit app.ts and not generated files. i will add build folder to .gitignore.

**Review by procoder-net — APPROVED** [review]

**Comment by procoder-net** [comment]
Test this with my latest change...we can then merge it.

**Review by procoder-net — CHANGES_REQUESTED** [review]
test this.

**Comment by shravancr95** [comment]
@procoder-net works, can we merge?

**Review by procoder-net — APPROVED** [review]

**Comment by procoder-net** [comment]
@shravancr95 write steps for Pg installation and up and running with this branch in wiki.

**Pull request merged**
